import 'dart:core';
import 'package:get/get.dart';
import 'package:shared_preferences/shared_preferences.dart';

String username = '';
var questionData = [];
String matchId = '';
RxString player = ''.obs;
RxString opponent = ''.obs;
double score = 0.0;
String participantId = '';
String competitionId = '';
String accessToken = '';
int userId = 0;
int competitionHour = 0;
int competitionMinute = 0;
int competitionSecond = 0;
int participantLevel = 0;
RxString round = "0".obs;
String competitionName = 'Competition Name';
RxBool isCompetitionWinner = false.obs;
String baseUrl = 'https://hackcbs-backend.onrender.com//';